// Additional original paragraphs give the authoring passages sustained argument
// and context, rather than a short list of facts written solely for gap fills.
export const readingSupplement = [
  [
    'The problem of naming proved more complicated than the founders had expected. Two donors might use the same name for visibly different beans, while a single variety could acquire a new name when a family moved to another village. The collection therefore kept the donor\'s description alongside its own measurements instead of replacing local names with supposedly definitive labels. This approach required more storage space in the database, but it preserved distinctions that might later turn out to matter. A variety valued for its taste could be physically similar to one selected for its ability to remain fresh after picking.',
    'Keeping records did not eliminate uncertainty. A seed packet could remain in a kitchen drawer for years before donation, and the donor might not remember when its contents had been harvested. Staff marked such dates as unknown rather than estimating them from the condition of the envelope. They also separated observations from explanations. A gardener\'s statement that a crop survived a dry season was recorded as an observation; a claim that the crop survived because of unusually deep roots required further evidence. Visitors sometimes found these qualifications frustrating, but researchers preferred an honest gap to a confident statement that could not be checked.',
    'The gardens introduced another challenge. Growing a variety in a new location could gradually change the characteristics of the seeds returned to storage. If members repeatedly chose only the earliest plants for seed, for example, later-flowering plants would become less common. The organisers asked growers to collect from several healthy plants rather than from a single exceptional specimen. They also distributed the same variety to more than one garden. No individual grower could guarantee preservation on their own, but several gardens reduced the chance that a flood, disease outbreak or missed harvest would destroy the entire living collection.',
    'Education became part of the work almost by accident. New members often assumed that preserving seeds meant leaving them untouched in a secure room. Demonstrations showed why periodic growing and testing were necessary. Staff compared the collection to a maintained workshop rather than a sealed time capsule: tools and records could survive only if people continued to use the relevant skills. Experienced gardeners taught newcomers how to recognise mature seed and keep varieties separate. In return, younger volunteers helped older members photograph crops and submit records without requiring them to become expert computer users.',
    'The founders did not claim that every saved variety would become commercially important. Some produced uneven crops or required more labour than modern alternatives. Their argument was that current popularity was a poor guide to future usefulness. A characteristic overlooked today might matter under different growing conditions. The collection also preserved knowledge of how people had used the plants, including recipes and harvesting practices. Its value lay partly in keeping several possible choices available. Measuring that value solely by the number of packets distributed each year would miss much of what the project was trying to retain.',
    'Visitors could examine a display of packets from successive harvests of the same variety. The display showed that preservation involved repeated decisions rather than one act of collection. A damaged label, a missed test or an undocumented choice of parent plants could affect what later users understood about the seeds. The volunteers therefore reviewed a small sample of records together each month. When they disagreed about an entry, they retained the original wording and added an explanation of the uncertainty. This slower process reduced the temptation to make the catalogue look more complete by hiding unresolved questions. It also helped new volunteers learn why apparently minor recording details deserved attention.',
  ],
  [
    'The sensors did not diagnose a fault by themselves. Each produced a stream of numbers that had to be interpreted in relation to a changing environment. A crowded festival afternoon naturally produced a different pattern from a quiet winter morning. Researchers initially tried comparing every reading with a single average, but that method generated too many warnings. They then grouped observations by conditions, allowing a new reading to be compared with earlier readings taken when the bridge was carrying similar traffic. The change reduced unnecessary inspections while preserving attention to unusual movements.',
    'Choosing where to attach the devices also required judgment. A sensor placed close to a joint could detect local movement very clearly but might say little about the middle of the span. Another position could reveal the bridge\'s overall motion while missing a small defect nearby. The team used a computer model to identify useful locations, then checked those choices with temporary equipment before fitting permanent units. The final arrangement represented a compromise. Covering every possible point would have created more data than the small maintenance team could reasonably inspect and maintain.',
    'For the council, reliability included the monitoring equipment itself. Batteries needed replacement, wireless connections could fail, and a damaged sensor could imitate the signal of a damaged bridge. The researchers therefore designed checks for missing or implausible readings. When one device reported a large change that nearby devices did not record, staff inspected the instrument before drawing conclusions about the structure. This did not mean ignoring isolated warnings. It meant recognising that measurement was a physical process with its own sources of error, rather than an effortless window onto the condition of the bridge.',
    'The project changed how maintenance was scheduled. Previously, inspections occurred at fixed intervals, with additional visits after exceptional storms. Continuous records made it possible to identify periods when closer attention was justified. Nevertheless, the engineers rejected a proposal to remove routine visual inspections altogether. A crack on an exposed surface, loose protective paint or trapped water might be visible before it measurably altered the bridge\'s vibration. Combining two kinds of evidence was more useful than declaring either one universally superior. Staff training consequently covered both reading the monitoring reports and recognising physical signs during a visit.',
    'Public communication presented a final difficulty. A notice saying that a sensor had detected an unusual movement could alarm residents even when the cause was harmless. Conversely, a general statement that the bridge was continuously monitored might suggest a guarantee that no failure was possible. The published report explained the distinction between detecting a change and establishing its cause. It also described what would happen after an alert and who could decide to restrict access. The council judged the trial useful, but its recommendation was for a complementary system of observation, not an automatic replacement for engineering responsibility.',
  ],
  [
    'The collection\'s growth soon forced the association to define what it would accept. Donors offered large pieces of furniture and obsolete electrical devices, reasoning that anything usable should be welcome. Storage and repair capacity were limited, however. The organisers began asking whether an object was likely to be borrowed often enough to justify the space and work it required. Rejecting a donation could be awkward, particularly when its owner attached sentimental value to it. A written acceptance policy helped volunteers explain that the decision concerned the service\'s purpose rather than the worth of the object itself.',
    'Borrowing also depended on trust, but trust did not mean the absence of rules. Members received a demonstration before taking unfamiliar powered equipment home. They agreed to report damage immediately rather than attempting a repair that might conceal the problem. Volunteers distinguished ordinary wear from careless use, recognising that heavily borrowed tools would eventually need replacement even if everyone handled them properly. A system that punished every failure would discourage honest reporting. Equally, ignoring repeated misuse would transfer its cost to other members and reduce the number of functioning items available.',
    'The online catalogue made the collection easier to search, yet it did not remove the need for conversation. A borrower might request a large drill when a smaller one was better suited to the job, or reserve a projector without realising that a particular cable was needed. Volunteers asked what the person hoped to accomplish and helped identify the appropriate equipment. They avoided doing the work for the borrower. The aim was to increase the member\'s ability to act independently, so a useful explanation could be as valuable as the temporary possession of a tool.',
    'Environmental claims required similar care. Sharing an object could prevent several households from buying their own, but this did not automatically establish the size of any environmental saving. Transport to collect and return equipment, repairs and replacement parts also used resources. The association recorded how borrowers travelled and whether they would otherwise have purchased the item. These responses could not provide a perfect calculation, because people did not always know what they would have done in a different situation. They nevertheless offered a more informative basis for discussion than assuming that every loan prevented a new purchase.',
    'The organisers eventually concluded that a single measure of success would distort the project. A popular ladder could produce many loans while teaching little; a rarely borrowed sewing machine might enable a member to acquire a lasting skill. Both uses mattered, but in different ways. Financial accounts were necessary to keep the doors open, and borrowing totals helped decide what to buy next. Interviews revealed benefits that neither measure captured. The association continued to publish all three kinds of information, accepting that a clear account of several outcomes was more honest than a dramatic claim based on one convenient number.',
  ],
]
