import { parseAssessmentPackage } from '@/domain/assessment'

// Authoring-only content, deliberately independent of the playable SAT set.
export const satAuthoringExample = parseAssessmentPackage({
  schemaVersion: 4, packageId: 'example-sat-style', revision: 1, source: 'built-in',
  title: 'SAT-style Authoring Example',
  description: 'A compact structural example with four fixed-order parts; not a full-length or official SAT.',
  metadata: { subject: 'College readiness', difficulty: 'standard', locale: 'en-US', shortLabel: 'SAT-style',
    disclaimer: 'Original practice content. Results are not official College Board scores.' },
  resources: [{ id: 'rectangle-reference', type: 'document', title: 'Rectangle reference',
    content: [{ type: 'math', expression: 'Area = length × width' }] }],
  review: { mode: 'answers' },
  parts: [
    { id: 'reading-1', groupTitle: 'Reading and Writing', title: 'Module 1', durationSeconds: 300, navigation: 'free', defaultLayout: 'split',
      tools: [{ type: 'mark_for_review' }, { type: 'option_eliminator' }],
      items: [
        { id: 'archive-detail', domain: 'Information and Ideas',
          stimulus: [{ type: 'passage', paragraphs: ['An archive digitised fragile maps so researchers could consult them without repeatedly unfolding the originals. Staff retained the paper maps because details of their construction were not captured in the scans.'] }],
          prompt: [{ type: 'text', text: 'Why did the archive retain the original maps?' }],
          interaction: { type: 'single_choice', options: [{ id: 'a', label: 'Some physical features were absent from digital copies.' }, { id: 'b', label: 'Researchers refused to use scans.' }, { id: 'c', label: 'The scans could not show place names.' }, { id: 'd', label: 'Paper maps took less storage space.' }] },
          scoring: { type: 'exact', answer: 'a' } },
        { id: 'cautious-language', domain: 'Craft and Structure',
          stimulus: [{ type: 'passage', paragraphs: ['The biologist called the result tentative because only a small number of samples had been examined.'] }],
          prompt: [{ type: 'text', text: 'In this sentence, tentative most nearly means' }],
          interaction: { type: 'single_choice', options: [{ id: 'a', label: 'permanent' }, { id: 'b', label: 'unrelated' }, { id: 'c', label: 'provisional' }, { id: 'd', label: 'accidental' }] },
          scoring: { type: 'exact', answer: 'c' } },
      ] },
    { id: 'reading-2', groupTitle: 'Reading and Writing', title: 'Module 2', durationSeconds: 300, navigation: 'free', defaultLayout: 'split',
      tools: [{ type: 'mark_for_review' }, { type: 'option_eliminator' }],
      items: [
        { id: 'visitor-table', domain: 'Information and Ideas',
          stimulus: [{ type: 'table', caption: 'Visitors to a science exhibition', columns: ['Day', 'Visitors'], rows: [['Monday', '120'], ['Tuesday', '180'], ['Wednesday', '150']] }],
          prompt: [{ type: 'text', text: 'Which statement accurately describes these visitor counts?' }],
          interaction: { type: 'single_choice', options: [{ id: 'a', label: 'Visitor counts rose every day.' }, { id: 'b', label: 'Tuesday had the most visitors.' }, { id: 'c', label: 'Wednesday had fewer visitors than Monday.' }, { id: 'd', label: 'Each day had at least 160 visitors.' }] },
          scoring: { type: 'exact', answer: 'b' } },
        { id: 'cause-transition', domain: 'Expression of Ideas',
          stimulus: [{ type: 'passage', paragraphs: ['Heavy snow blocked the mountain road. ____, the delivery arrived a day later than planned.'] }],
          prompt: [{ type: 'text', text: 'Choose the transition that expresses the relationship between these events.' }],
          interaction: { type: 'single_choice', options: [{ id: 'a', label: 'In contrast' }, { id: 'b', label: 'For instance' }, { id: 'c', label: 'Meanwhile' }, { id: 'd', label: 'As a result' }] },
          scoring: { type: 'exact', answer: 'd' } },
      ] },
    { id: 'math-1', groupTitle: 'Math', title: 'Module 1', durationSeconds: 300, navigation: 'free', defaultLayout: 'single',
      tools: [{ type: 'calculator' }, { type: 'reference_document', resourceId: 'rectangle-reference' }],
      items: [
        { id: 'linear-cost', domain: 'Algebra', stimulus: [{ type: 'math', expression: '4y − 9 = 35' }],
          prompt: [{ type: 'text', text: 'Find y in the displayed equation.' }], interaction: { type: 'numeric_entry' }, scoring: { type: 'numeric', answer: 11 } },
        { id: 'rectangle-area', domain: 'Geometry', prompt: [{ type: 'text', text: 'A rectangle is 9 metres long and 5 metres wide. What is its area in square metres?' }],
          interaction: { type: 'single_choice', options: [{ id: 'a', label: '14' }, { id: 'b', label: '28' }, { id: 'c', label: '45' }, { id: 'd', label: '90' }] }, scoring: { type: 'exact', answer: 'c' } },
      ] },
    { id: 'math-2', groupTitle: 'Math', title: 'Module 2', durationSeconds: 300, navigation: 'free', defaultLayout: 'split',
      tools: [{ type: 'calculator' }, { type: 'reference_document', resourceId: 'rectangle-reference' }],
      items: [
        { id: 'volunteer-hours', domain: 'Data Analysis',
          stimulus: [{ type: 'bar_chart', title: 'Volunteer hours', unit: 'hours', bars: [{ label: 'Leila', value: 15 }, { label: 'Omar', value: 21 }, { label: 'Nina', value: 18 }] }],
          prompt: [{ type: 'text', text: 'How many more hours did Omar volunteer than Leila?' }], interaction: { type: 'numeric_entry' }, scoring: { type: 'numeric', answer: 6 } },
        { id: 'quadratic-positive', domain: 'Advanced Math', stimulus: [{ type: 'math', expression: 'z² = 81' }],
          prompt: [{ type: 'text', text: 'What is the positive value of z?' }], interaction: { type: 'numeric_entry' }, scoring: { type: 'numeric', answer: 9 } },
      ] },
  ],
})
