import { choice, numeric } from './helpers';
const a = 'Algebra';
const m = 'Advanced Math';
const p = 'Problem-Solving and Data Analysis';
const g = 'Geometry and Trigonometry';
export const math2 = [
  choice('sat-m2-01', a, 'Linear equations in one variable', '', 'What value of x satisfies 5(2x − 3) = 3x + 20?', ['5', '7', '10', '35'], 'a', [{ type: 'math', expression: '5(2x − 3) = 3x + 20' }]),
  numeric('sat-m2-02', a, 'Systems of two linear equations', 'For what value of k does the system shown have no solution?', 4, [{ type: 'math', expression: '3x + 2y = 14\n6x + ky = 20' }]),
  choice('sat-m2-03', a, 'Linear functions', 'A service charges a fixed monthly fee plus an additional charge for each minute of use. The total monthly charge C, in dollars, for m minutes of use is C = 45 + 0.18m.', 'Which statement correctly interprets 0.18 in this equation?', ['The fixed monthly charge is $0.18.', 'The total charge is $0.18 for 45 minutes.', 'Each additional minute of use adds $0.18 to the charge.', 'Each additional dollar pays for 0.18 minutes of use.'], 'c'),
  choice('sat-m2-04', a, 'Linear inequalities', '', 'Which inequality is equivalent to 6x − 5 > 2x + 19?', ['x > 4', 'x > 6', 'x < 6', 'x > 24'], 'b'),
  choice('sat-m2-05', a, 'Systems of two linear equations', '', 'Two numbers have a sum of 31. The larger number is 1 more than twice the smaller number. What is the larger number?', ['10', '15', '20', '21'], 'd'),
  choice('sat-m2-06', a, 'Systems of two linear equations', '', 'The lines y = 2x + 1 and y = −x + 13 intersect at (x, y). What is the value of y at the intersection?', ['4', '5', '8', '9'], 'd', [{ type: 'math', expression: 'y = 2x + 1\ny = −x + 13' }]),
  choice('sat-m2-07', a, 'Linear functions', '', 'For the linear function f, f(2) = 7 and f(5) = 19. What is f(0)?', ['−4', '−1', '1', '4'], 'b'),
  choice('sat-m2-08', a, 'Systems of two linear equations', 'A laboratory combines x milliliters of a 30% salt solution with y milliliters of a 50% salt solution. The mixture has a total volume of 300 milliliters and contains 120 milliliters of salt. Volumes are assumed to add.', 'What is the value of y?', ['60', '120', '150', '180'], 'c'),
  choice('sat-m2-09', m, 'Quadratic equations', '', 'What is the greater solution of x² − 10x + 21 = 0?', ['7', '10', '14', '21'], 'a'),
  choice('sat-m2-10', m, 'Equivalent expressions', '', 'For x ≠ 4 and x ≠ −2, which expression is equivalent to (x² − 16)/(x² − 2x − 8)?', ['(x − 4)/(x − 2)', '(x + 4)/(x − 2)', '(x − 4)/(x + 2)', '(x + 4)/(x + 2)'], 'd', [{ type: 'math', expression: '(x² − 16)/(x² − 2x − 8)' }]),
  numeric('sat-m2-11', m, 'Quadratic functions', 'The graph of y = (x − 3)² + k passes through the point (1, 13). What is the value of k?', 9),
  choice('sat-m2-12', m, 'Exponential functions', 'The table shows values of an exponential function f. The ratio of f(x + 1) to f(x) is constant.', 'Which equation defines f?', ['f(x) = 81 − 54x', 'f(x) = 81(1/3)ˣ', 'f(x) = 27(1/3)ˣ', 'f(x) = 81(3)ˣ'], 'b', [{ type: 'table', columns: ['x', 'f(x)'], rows: [['0', '81'], ['1', '27'], ['2', '9']] }]),
  choice('sat-m2-13', m, 'Quadratic equations with constants', '', 'The equation x² + 6x + c = 0 has exactly one real solution. What is the value of c?', ['3', '6', '9', '36'], 'c'),
  numeric('sat-m2-14', m, 'Nonlinear equations in context', 'A rectangular garden has perimeter 40 meters and area 96 square meters. What is the length, in meters, of the longer side?', 12),
  choice('sat-m2-15', m, 'Polynomial functions', 'A quadratic function f has zeros at x = −2 and x = 5. Its graph passes through the point (0, −20).', 'Which equation defines f?', ['f(x) = (x + 2)(x − 5)', 'f(x) = −2(x + 2)(x − 5)', 'f(x) = 2(x − 2)(x + 5)', 'f(x) = 2(x + 2)(x − 5)'], 'd'),
  choice('sat-m2-16', p, 'Ratios, rates, and units', '', 'A machine produces 240 identical parts in 3 hours at a constant rate. At this rate, how many minutes does the machine need to produce 100 parts?', ['75', '80', '100', '125'], 'a'),
  choice('sat-m2-17', p, 'Two-variable data', 'A researcher models the relationship between the number of hours h that a battery has been used and its remaining charge C, in percent, with the equation C = 100 − 7.5h. The model is intended for use while the predicted charge remains nonnegative.', 'According to the model, after how many hours will the battery have 40% charge remaining?', ['5.33', '6', '8', '10'], 'c'),
  numeric('sat-m2-18', p, 'Conditional probability', 'The table summarizes 60 students by club membership and year in school. One of the students who belongs to the science club is selected at random. What is the probability that this student is a senior? Enter a decimal or a fraction.', 0.6, [{ type: 'table', caption: 'Student club membership', columns: ['Year', 'Science club', 'Not in science club'], rows: [['Junior', '12', '18'], ['Senior', '18', '12']] }]),
  choice('sat-m2-19', p, 'Evaluating statistical claims', 'A school randomly assigned 120 students to use either a new study app or their usual study materials for four weeks. The group using the app had a higher mean score on a common final test.', 'Which feature of the study most directly supports investigating whether the app caused the difference in scores?', ['The study lasted exactly four weeks.', 'Students were randomly assigned to the two groups.', 'The school had more than 120 students.', 'The final test produced numerical scores.'], 'b'),
  choice('sat-m2-20', g, 'Similar triangles', 'Two triangles are similar. A side of the smaller triangle has length 6 and corresponds to a side of length 15 in the larger triangle. The area of the smaller triangle is 24 square units.', 'What is the area of the larger triangle, in square units?', ['60', '96', '120', '150'], 'd'),
  numeric('sat-m2-21', g, 'Circles in the coordinate plane', 'The equation of a circle is x² + y² − 6x + 8y = 0. What is the radius of the circle?', 5, [{ type: 'math', expression: 'x² + y² − 6x + 8y = 0' }]),
  choice('sat-m2-22', g, 'Right-triangle trigonometry', 'In right triangle ABC, angle C is 90°, AC = 8, BC = 15, and AB = 17.', 'What is sin(A)?', ['15/17', '8/17', '8/15', '15/8'], 'a'),
];
