import type { AssessmentItem } from '@/domain/assessment'

const options = (labels: string[], prefix = '') => labels.map((label, index) => ({ id: `${prefix}${String.fromCharCode(97 + index)}`, label }))
type ReadingRow = [passage: string, question: string, choices: string[], answer: string]
const reading: ReadingRow[] = [
  ['A fictional historian studying a port discovered that the number of recorded disputes rose after a commercial court opened. Earlier accounts had interpreted this increase as evidence of worsening relations among merchants. The historian instead notes that the new court charged lower fees and accepted complaints that private arbitration had excluded. The records may therefore reflect a change in access to dispute resolution rather than a change in the frequency of disagreement.', 'The passage primarily serves to', ['deny that merchants disagreed before the court opened', 'offer an alternative explanation for an observed increase in recorded disputes', 'prove that the court resolved every commercial disagreement', 'compare the legal systems of two different ports', 'argue that private arbitration was less expensive than litigation'], 'b'],
  ['A fictional historian studying a port discovered that the number of recorded disputes rose after a commercial court opened. Earlier accounts had interpreted this increase as evidence of worsening relations among merchants. The historian instead notes that the new court charged lower fees and accepted complaints that private arbitration had excluded. The records may therefore reflect a change in access to dispute resolution rather than a change in the frequency of disagreement.', 'Which finding would most strengthen the historian\'s alternative explanation?', ['The port imported more than one kind of grain.', 'The court occupied a former warehouse.', 'Some disputes involved merchants from other towns.', 'The increase consisted largely of small claims that earlier arbitration rules would not have admitted.', 'Several merchants owned ships jointly.'], 'd'],
  ['In an imagined experiment, a biologist removed a dominant grass from several plots and found that smaller plants subsequently became more abundant. A colleague pointed out that removing the grass disturbed the soil as well as reducing competition for light. The biologist repeated the experiment with additional plots in which the soil was disturbed but the grass remained. The smaller plants increased substantially only where the grass had been removed.', 'The additional plots were introduced primarily to', ['measure the age of the smaller plants', 'test a competing explanation for the first experiment\'s result', 'ensure that every plot contained the same number of species', 'determine whether light was the only resource used by plants', 'demonstrate that soil disturbance always benefits dominant grasses'], 'b'],
  ['In an imagined experiment, a biologist removed a dominant grass from several plots and found that smaller plants subsequently became more abundant. A colleague pointed out that removing the grass disturbed the soil as well as reducing competition for light. The biologist repeated the experiment with additional plots in which the soil was disturbed but the grass remained. The smaller plants increased substantially only where the grass had been removed.', 'Which conclusion is best supported by the repeated experiment?', ['The smaller plants require disturbed soil in every habitat.', 'The dominant grass benefits from increased light.', 'Soil disturbance alone does not adequately explain the observed increase in smaller plants.', 'Competition for water was completely absent.', 'The colleague\'s concern could have been dismissed without testing.'], 'c'],
  ['Critics often describe the fictional poet Arlen\'s late work as a retreat from public concerns because its settings are domestic. Yet the poems repeatedly connect household routines to conditions beyond the home: a shortage changes a meal, a distant conflict interrupts a letter, and new working hours alter a family\'s conversation. The change of setting may represent a different way of examining public life rather than its abandonment.', 'The author\'s attitude toward the critics\' interpretation is best described as', ['qualified disagreement supported by attention to the poems\' details', 'unreserved approval based on the poet\'s biography', 'indifference to the distinction between early and late work', 'hostility to all interpretation of domestic settings', 'acceptance of the conclusion but rejection of its evidence'], 'a'],
  ['A fictional transport study found that passengers rated a bus service more favorably after electronic arrival signs were installed, even though average waiting times did not change. The researchers suggested that uncertainty had contributed substantially to dissatisfaction. They did not claim that information could compensate for arbitrarily long waits, only that predictable and unpredictable waits of similar length might be experienced differently.', 'Which statement is most consistent with the researchers\' interpretation?', ['Arrival signs eliminated delays.', 'Actual waiting time never affects satisfaction.', 'Passengers prefer inaccurate information to no information.', 'Only passengers with very short journeys use arrival signs.', 'Reducing uncertainty can improve the experience of a wait without shortening it.'], 'e'],
  ['A fictional transport study found that passengers rated a bus service more favorably after electronic arrival signs were installed, even though average waiting times did not change. The researchers suggested that uncertainty had contributed substantially to dissatisfaction. They did not claim that information could compensate for arbitrarily long waits, only that predictable and unpredictable waits of similar length might be experienced differently.', 'The final sentence primarily functions to', ['introduce evidence that contradicts the study', 'identify a limitation on the proposed interpretation', 'assert that all delays are equally tolerable', 'explain how the signs were manufactured', 'replace the satisfaction measure with a financial measure'], 'b'],
  ['In a fictional archaeological debate, researchers agree that a group of clay tablets records deliveries of grain. They disagree about whether the tablets describe taxes or voluntary exchanges. Uniform quantities support the tax interpretation, but standardized package sizes could produce the same pattern in trade. Without evidence identifying the parties\' obligations, the numerical regularity does not settle the issue.', 'Which assumption would be required to infer taxation from uniform quantities alone?', ['The tablets were written in more than one year.', 'Grain can be stored for long periods.', 'Voluntary exchanges would not also tend to use standardized quantities.', 'Every tablet names a different recipient.', 'The tablets were found near a river.'], 'c'],
  ['A fictional study compares the vocabulary in printed novels from two centuries. The authors warn that the surviving books are not a random sample of everything once published. Libraries preferentially preserved certain genres, and inexpensive editions were often discarded. A change in the sample\'s vocabulary might therefore arise partly from differences in preservation rather than from a general change in language.', 'Which finding would most reduce the concern described in the passage?', ['Books in both centuries varied in length.', 'Several novels were reprinted more than once.', 'Some libraries owned books from both centuries.', 'The observed vocabulary change persists within each genre after comparable editions are sampled.', 'Printed books contain punctuation as well as words.'], 'd'],
  ['In an imagined experiment, a new coating reduced corrosion on metal samples kept in dry air but had little effect in humid conditions. The authors recommended its use in climate-controlled storage while withholding a recommendation for outdoor structures. Their conclusion distinguished a useful result in a limited setting from evidence of general effectiveness.', 'Which statement best characterizes the authors\' recommendation?', ['It is narrower than a claim that the coating works under all conditions.', 'It ignores the dry-air results.', 'It assumes that outdoor humidity is constant.', 'It treats lack of effect as evidence of increased corrosion.', 'It recommends replacing all existing protective methods.'], 'a'],
]

// Independent choice groups preserve the all-or-nothing GRE completion rule.
type CompletionRow = [text: string, groups: string[][], answers: number[]]
const completion: CompletionRow[] = [
  ['The reviewer praised the historian\'s willingness to acknowledge gaps in the evidence; such _____ made the argument more credible, not less.', [['candor', 'verbosity', 'dogmatism', 'haste', 'indifference']], [0]],
  ['Because the committee had not agreed on its central objective, its discussion was _____, moving between unrelated proposals without resolving any of them.', [['methodical', 'conclusive', 'desultory', 'prescient', 'impartial']], [2]],
  ['The field report was (i) _____ about the cause of the decline, but (ii) _____ in its recommendation that monitoring should continue until competing explanations could be tested.', [['categorical', 'circumspect', 'flippant'], ['unequivocal', 'evasive', 'indifferent']], [1, 0]],
  ['The critic\'s initial response was (i) _____: she welcomed the novel\'s ambition but questioned its execution. Her later review was more (ii) _____, openly praising what she had first treated with reservation.', [['ambivalent', 'ecstatic', 'hostile'], ['dismissive', 'laudatory', 'cryptic']], [0, 1]],
  ['The theory remained _____ until new observations supplied a way to test its central prediction; prior debate had depended largely on assumptions that neither side could verify.', [['empirical', 'speculative', 'obsolete', 'redundant', 'unanimous']], [1]],
  ['Although the archive was (i) _____ in size, its records were (ii) _____: almost every document concerned the same narrow administrative procedure, leaving other aspects of town life obscure.', [['meager', 'immense', 'portable'], ['homogeneous', 'contradictory', 'illegible']], [1, 0]],
  ['The researcher did not (i) _____ earlier findings outright. Instead, she sought to (ii) _____ their scope, showing that a result valid under laboratory conditions was not necessarily (iii) _____ to every natural setting.', [['repudiate', 'corroborate', 'publicize'], ['inflate', 'delimit', 'obscure'], ['applicable', 'hostile', 'irrelevant']], [0, 1, 0]],
  ['The official statement appeared (i) _____, promising immediate reform. Yet its provisions were (ii) _____, leaving every major decision to a later committee. The contrast between confident language and deferred action made the promise seem (iii) _____.', [['hesitant', 'decisive', 'incoherent'], ['noncommittal', 'irrevocable', 'punitive'], ['hollow', 'meticulous', 'belated']], [1, 0, 0]],
  ['What seemed an (i) _____ custom to outsiders was, for residents, thoroughly (ii) _____: it organized the exchange of work during the short harvest season and had an obvious practical purpose.', [['inscrutable', 'indispensable', 'ordinary'], ['intelligible', 'arbitrary', 'unprecedented']], [0, 0]],
]

type EquivalenceRow = [text: string, choices: string[], answers: string[]]
const equivalence: EquivalenceRow[] = [
  ['The editor\'s comments were unusually _____; every criticism identified a particular sentence and proposed a specific way to improve it.', ['vague', 'precise', 'hostile', 'exact', 'lengthy', 'evasive'], ['b', 'd']],
  ['Despite repeated invitations to discuss the disputed measurements, the investigator remained _____, declining to express any opinion before completing the analysis.', ['reticent', 'loquacious', 'reckless', 'guarded', 'jubilant', 'didactic'], ['a', 'd']],
  ['The negotiations were _____, with both sides yielding on minor points so that agreement on the central issue could be reached.', ['acrimonious', 'conciliatory', 'futile', 'accommodating', 'clandestine', 'perfunctory'], ['b', 'd']],
  ['The supposedly permanent arrangement proved _____, lasting only until a change in leadership made an entirely different policy possible.', ['transitory', 'equitable', 'onerous', 'explicit', 'ephemeral', 'durable'], ['a', 'e']],
  ['The lecturer\'s account was _____, presenting the essential argument in a few carefully chosen sentences without omitting any necessary step.', ['convoluted', 'succinct', 'digressive', 'tentative', 'terse', 'inaccurate'], ['b', 'e']],
  ['Because the artifact\'s origin could not be established from either documents or physical evidence, every confident attribution seemed _____.', ['justified', 'unfounded', 'routine', 'baseless', 'verifiable', 'exhaustive'], ['b', 'd']],
  ['The reformer was _____ in pursuing the proposal, returning to it after each defeat and refusing to abandon its central objective.', ['tenacious', 'capricious', 'diffident', 'resolute', 'complacent', 'tractable'], ['a', 'd']],
  ['The committee found the two accounts _____: their descriptions of the same event differed in ways that could not both be true.', ['compatible', 'incompatible', 'meticulous', 'irreconcilable', 'interchangeable', 'plausible'], ['b', 'd']],
]

export function verbalExample(module: 0 | 1): AssessmentItem[] {
  const rc = reading.slice(module * 5, module * 5 + 5).map(([passage, question, choices, answer], index): AssessmentItem => ({
    id: `gre-v${module + 1}-reading-${index + 1}`, domain: 'Verbal Reasoning', skill: 'Reading comprehension',
    stimulus: [{ type: 'passage', paragraphs: [passage] }], prompt: [{ type: 'text', text: question }],
    interaction: { type: 'single_choice', options: options(choices) }, scoring: { type: 'exact', answer }, presentation: { layout: 'split', stimulusLabel: 'Passage' },
  }))
  const tc = completion.slice(module === 0 ? 0 : 4, module === 0 ? 4 : 9).map(([text, groups, answers], index): AssessmentItem => {
    const id = `gre-v${module + 1}-completion-${index + 1}`
    return { id, domain: 'Verbal Reasoning', skill: 'Text completion', stimulus: [], prompt: [{ type: 'text', text }],
      interaction: { type: 'grouped_choice', groups: groups.map((labels, i) => ({ id: `blank-${i + 1}`, label: `Blank ${i + 1}`, options: options(labels, `b${i + 1}-`) })) },
      scoring: { type: 'mapping', answers: Object.fromEntries(answers.map((answer, i) => [`blank-${i + 1}`, `b${i + 1}-${String.fromCharCode(97 + answer)}`])) } }
  })
  const se = equivalence.slice(module === 0 ? 0 : 3, module === 0 ? 3 : 8).map(([text, choices, answers], index): AssessmentItem => ({
    id: `gre-v${module + 1}-equivalence-${index + 1}`, domain: 'Verbal Reasoning', skill: 'Sentence equivalence', stimulus: [],
    prompt: [{ type: 'text', text: `${text}\nChoose two answers that complete the sentence with equivalent meanings.` }],
    interaction: { type: 'multiple_choice', minimumSelections: 2, maximumSelections: 2, options: options(choices) }, scoring: { type: 'set', answers },
  }))
  if (module === 1) rc[4] = {
    id: 'gre-v2-reading-5', domain: 'Verbal Reasoning', skill: 'Reading comprehension, multiple answers',
    stimulus: [{ type: 'passage', paragraphs: ['In an imagined experiment, a new coating reduced corrosion on metal samples kept in dry air but had little effect in humid conditions. The authors recommended it for climate-controlled storage while withholding a recommendation for outdoor structures. They called for further tests at intermediate humidity levels.'] }],
    prompt: [{ type: 'text', text: 'Which statements are supported by the passage? Select all that apply.' }],
    interaction: { type: 'multiple_choice', minimumSelections: 1, maximumSelections: 3, options: options([
      'The coating performed differently under different humidity conditions.',
      'The authors established that the coating increases corrosion outdoors.',
      'The authors considered further humidity testing worthwhile.',
    ]) }, scoring: { type: 'set', answers: ['a', 'c'] }, presentation: { layout: 'split', stimulusLabel: 'Passage' },
  }
  return [...tc, ...rc, ...se]
}
